---
#
# Ansible playbook to upgrade the OS image of a network device.
#

- name: RELOAD SWITCH AND VERIFY NEW SOFTWARE VERSION
  hosts: all
  gather_facts: false
  connection: network_cli
  strategy: free
  become: yes

  tasks:

    - name: SAVE RUNNING CONFIG
      cli_command:
        command: write

    - name: RELOAD SWITCH
      cli_command:
        command: reload
        prompt: .*
        answer: y

    - name: RESET SSH CONNECTION
      meta: reset_connection

    - name: WAIT FOR DEVICE TO BE RELOADED
      wait_for_connection:
        delay: 60
        timeout: 1200

    - name: GET NEW SOFTWARE VERSION
      cli_command:
        command: show version
      register: SHOWVER
     
    - local_action: copy content="{{ SHOWVER }}" dest="./{{ inventory_hostname }}_show-ver.txt_{{ ansible_date_time.date }}"
